### ISSUE TITLE
Feedbak on Mini Ex 3 by Winnie Soon

### ISSUE THREAD

**Issue by siusoon** [kris03/AP-17#2]
WHere is your mini ex 3?

**Comment by kris03** [comment]
Hi Winnie,
Sorry I'll admit that I forgot to upload it yesterday. 
So I rushed to do it now, but I'm having some problems getting it to work. My own HTML index file is working fine, but when I try to make a link for others to run it, it is not working..

**Comment by SylvesterSA** [comment]
Feedback on Mini ex_3 by Sylvester Schelde Andersen

First of all, judging on your message on here, maybe the work was supposed to "do" something? Nothing happened for me atleast, and by looking at the sourcecode i couldn't find any indication of movement (be it via throbber or whatever). 
So by that im not sure i would call this a throbber, but more a painting made with figures. (the source code being mainly rect, acr and fill). 
This leaves the work with big opportunity for improvement. 
What i like about this, is the aesthetics of the picture. It is obvious you put a lot of effort into making the burger and the colouring. Now you just need to add a throbber. 
Sidenote: What purpose does the push(), pop() function serve here? (also asking for myself..)
